### PR TITLE
Connect.prototype.isConnected added for compatibility with connect-ts…

### PR DESCRIPTION
**Pull request by eaglus**
…-api

### CODE REVIEW

**Comment by spirinvladimir** [comment]
What for this changes?

**Comment by spirinvladimir** [comment]
Ok. I got an idea not to use connect.state.isConnected() and use connect.isConnected(). Am I right?

**Comment by eaglus** [comment]
Connect.prototype.isConnected added for compatibility with connect-ts-api.
This commit synchronizes API of connect-ts-api and connect-js-api, for using connect-js-api as connect-ts-api (before this commit connect-js-api haven't Connect.prototype.isConnected method).

**Comment by spirinvladimir** [comment]
Thanks

**Pull request merged**
